role.basicUser:   BASIC_USER
role.adminUser:   ADMIN
role.premiumUser: PREMIUM_USER
role.labelUser:   LABEL_USER
role.artistUser:  ARTIST_USER

query.recentFavoritesToQuery: 3
query.listeningHistoryToQuery: 25