role.basicUser:   BASIC_USER
role.adminUser:   ADMIN
role.premiumUser: PREMIUM_USER
role.labelUser:   LABEL_USER
role.artistUser:  ARTIST_USER

query.recentFavoritesToQuery: 3
query.relatedArtistsToQuery: 20
query.listeningHistoryToQuery: 25

email.emailAddress:           "Musio.SBU@gmail.com"
email.changePasswordSubject:  "Change Musio Password"
email.changePasswordBody:     "Here is your one time security code for changing your password.\nPlease enter it into the confirmation dialog.\n\n"

mimetype.jpeg:   jpeg
mimetype.png:    png
mimetype.vorbis: vorbis