import { NgModule } from '@angular/core';
import {
    MatToolbarModule,
    MatInputModule,
    MatButtonModule,
    MatProgressSpinnerModule,
    MatCardModule,
    MatIconModule,
    MatTooltipModule,
    MatPaginatorModule,
    MatTableModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatCheckboxModule,
    MatSnackBarModule,
    MatMenuModule,
    MatSelectModule,
    MatRadioModule,
    MatDialogModule,
    MatSidenavModule,
    MatExpansionModule,
    MatTabsModule,
    MatGridListModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatStepperModule
} from '@angular/material';
@NgModule({
    imports: [MatToolbarModule,
        MatInputModule,
        MatButtonModule,
        MatProgressSpinnerModule,
        MatCardModule,
        MatIconModule,
        MatTooltipModule,
        MatPaginatorModule,
        MatTableModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatCheckboxModule,
        MatSnackBarModule,
        MatMenuModule,
        MatSelectModule,
        MatRadioModule,
        MatDialogModule,
        MatSidenavModule,
        MatExpansionModule,
        MatTabsModule,
        MatGridListModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatStepperModule],

    exports: [MatToolbarModule,
        MatInputModule,
        MatButtonModule,
        MatProgressSpinnerModule,
        MatCardModule,
        MatIconModule,
        MatTooltipModule,
        MatPaginatorModule,
        MatTableModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatCheckboxModule,
        MatSnackBarModule,
        MatMenuModule,
        MatSelectModule,
        MatRadioModule,
        MatDialogModule,
        MatSidenavModule,
        MatExpansionModule,
        MatTabsModule,
        MatGridListModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatStepperModule]
})

export class SharedModule { }
